#!/bin/sh

DEBUG=${DEBUG:-false}

if [ $# -ne 1 ]; then
    echo "usage: $(basename $0) directory"
    exit 1
fi

DIR="$1"
shift

if [ ! -d "$DIR" ]; then
    echo "$DIR is not a directory"
    exit 1
fi

$DEBUG && echo "Running in $DIR"
cd "$DIR"

if ! [ -r docker-compose.yml ]; then
    echo "docker-compose.yml not found"
    exit 1
fi

DORESTART=0
for SERVICE in $(docker-compose ps --services); do
    # get container hash
    CONTAINER=$(docker-compose ps -q $SERVICE)
    if [ -z $CONTAINER ]; then
        echo "$PROJ is not running, not updating"
        exit 0
    fi
    
    # get image name and tag
    IMAGE=$(docker inspect $CONTAINER | jq -r '.[].Config.Image')

    # update image from 
    $DEBUG && echo "Trying to pull $IMAGE for $SERVICE"
    docker-compose pull -q "$SERVICE"

    HASHLATEST=$(docker images --no-trunc --format '{{.ID}}' "$IMAGE")
    HASHCURRENT=$(docker inspect $CONTAINER | jq -r '.[0].Image')

    if [ "$HASHLATEST" != "$HASHCURRENT" ]; then
        if $DEBUG; then
            echo "Found update for $IMAGE:"
            echo "  CURRENT $HASHCURRENT"
            echo "  LATEST  $HASHLATEST"
        fi        
        DORESTART=1
    else
        $DEBUG && echo "No update for $IMAGE"
    fi
done

if [ $DORESTART -eq 1 ]; then
    $DEBUG && echo "Recreating containers"
    docker-compose down
    docker-compose up -d --no-color
fi

exit 0
