#!/bin/sh

DEBUG=${DEBUG:-false}
COMPOSEFILENAME=${COMPOSEFILENAME:-"docker-compose.yml docker-compose.yaml compose.yml compose.yaml"}
DOCKER=${DOCKER:-docker}
COMPOSE=${COMPOSE:-docker-compose}

if [ $# -lt 1 ]; then
    echo "usage: $(basename $0) DIR [DIR ...]"
    exit 1
fi

while [ $# -gt 0 ]; do
    DIR="$1"
    shift

    if [ ! -d "$DIR" ]; then
        echo "$DIR is not a directory, skipping"
        continue
    fi

    $DEBUG && echo "Running in $DIR"
    cd "$DIR"

    COMPOSEFILEFOUND=0
    for f in $COMPOSEFILENAME; do
        $DEBUG && echo "Checking for $f"
        if [ -r $f ]; then
            $DEBUG && echo "Found $f"
            COMPOSEFILEFOUND=1
            break
        fi
    done
    if [ $COMPOSEFILEFOUND -eq 0 ]; then
        echo "Compose file not found"
        continue
    fi

    DORESTART=0
    for SERVICE in $($COMPOSE ps --services); do
        # get container hash
        CONTAINER=$($COMPOSE ps -q $SERVICE)
        if [ -z $CONTAINER ]; then
            echo "$SERVICE is not running, not updating"
            break
        fi

        # get image name and tag
        IMAGE=$($DOCKER inspect $CONTAINER | jq -r '.[].Config.Image')
        IMAGEDIGESTS=$($DOCKER image inspect $IMAGE | jq '.[].RepoDigests | length')
        if [ $IMAGEDIGESTS -eq 0 ]; then
            $DEBUG && echo "Trying to build local image $IMAGE for $SERVICE"
            $COMPOSE build -q --pull "$SERVICE"
        else
            $DEBUG && echo "Trying to pull $IMAGE for $SERVICE"
            $COMPOSE pull -q "$SERVICE"
        fi

	# remove docker.io prefix from image name
	IMAGE="${IMAGE#docker.io/}"

	# remove library prefix from image name
	IMAGE="${IMAGE#library/}"

        HASHLATEST=$($DOCKER images --no-trunc --format '{{.ID}}' "$IMAGE" | head -1)
        if [ x"$HASHLATEST" = x ]; then
            echo "Error looking up latest image hash for '$IMAGE' in service '$SERVICE'"
            break
        fi

        HASHCURRENT=$($DOCKER inspect $CONTAINER | jq -r '.[0].Image')

        if [ "$HASHLATEST" != "$HASHCURRENT" ]; then
            if $DEBUG; then
                echo "Found update for $IMAGE:"
                echo "  CURRENT $HASHCURRENT"
                echo "  LATEST  $HASHLATEST"
            fi
            DORESTART=1
        else
            $DEBUG && echo "No update for $IMAGE"
        fi
    done

    if [ $DORESTART -eq 1 ]; then
        $DEBUG && echo "Recreating containers"
        $COMPOSE --ansi=never down
        $COMPOSE --ansi=never up -d --no-color
    fi
done

exit 0
